[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
racing_smart_contract = "8Bt6v2aVESaAf2yGw8xjFY8R1YKgXbt4eDq5YcVKQVCf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=650bb4db-b1d0-4641-b7e1-afdea19a34c9"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/01-*.ts tests/**/02-*.ts"
test-pump = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/07-*.ts tests/**/08-*.ts"
test-race-multi = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/06-*.ts"
test-race-once = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/05-*.ts"
test-ray-amm-swap-base-in = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/09-*.ts"
test-ray-amm-swap-base-out = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/10-*.ts"
